baseURL = "https://0xmid00.github.io/"
languageCode = "en-us"
title = "Your Site Title"

theme = "tale"

# Enable all content types for rendering
disableKinds = []

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 2

